name: Create multi-arch Docker manifest
description: Combine platform-specific Docker images into a single multi-arch manifest
inputs:
  image-name:
    required: true
    description: Docker image name (e.g., org/image-name)
  dockerhub-user:
    required: true
    description: DockerHub username
  dockerhub-password:
    required: true
    description: DockerHub password
  metadata-tags:
    description: Docker metadata-action tags input. See https://github.com/docker/metadata-action#tags-input
    required: false
    default: |
      type=ref,event=branch
      type=ref,event=pr
      type=semver,pattern={{version}}
      type=semver,pattern={{major}}.{{minor}}
      type=semver,pattern={{major}}
  metadata-flavor:
    description: Docker metadata-action flavor input. See https://github.com/docker/metadata-action#flavor-input
    required: false
    default: latest=false
  sources:
    required: true
    description: |
      List of source images to combine (one per line).
      Can be full image references with digests (e.g., org/image@sha256:abc123)
      or image references with tags (e.g., org/image:1.0.0-amd64)
outputs:
  manifest:
    description: The created manifest reference (first tag from metadata)
    value: ${{ steps.create.outputs.manifest }}
  tags:
    description: All tags generated by metadata-action (newline separated)
    value: ${{ steps.meta.outputs.tags }}
  metadata-json:
    description: JSON output from metadata-action
    value: ${{ steps.meta.outputs.json }}

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-user }}
        password: ${{ inputs.dockerhub-password }}

    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image-name }}
        flavor: ${{ inputs.metadata-flavor }}
        tags: ${{ inputs.metadata-tags }}

    - name: Create manifest
      id: create
      shell: bash
      env:
        IMAGE_NAME: ${{ inputs.image-name }}
        METADATA_TAGS: ${{ steps.meta.outputs.tags }}
        SOURCES: ${{ inputs.sources }}
      run: |
        # Convert newline-separated tags from metadata to comma-separated
        TAGS=$(echo "$METADATA_TAGS" | sed 's|^[^:]*:||' | paste -sd ',' -)

        echo "Generated tags: $TAGS"

        ${{ github.action_path }}/create-manifest.sh \
          "$IMAGE_NAME" \
          "$TAGS" \
          "$SOURCES"
