name: Create multi-arch Docker manifest
description: Combine platform-specific Docker images into a single multi-arch manifest
inputs:
  docker-config-file:
    required: false
    description: Path to the docker config file (defaults to .docker-config.json) Must contain imageName, may contain metadata-tags and metadata-flavor.
    default: .docker-config.json
  image-name:
    required: false
    description: Docker image name (e.g., org/image-name). If not provided, read from config file.
  dockerhub-user:
    required: true
    description: DockerHub username
  dockerhub-password:
    required: true
    description: DockerHub password
  metadata-tags:
    description: Docker metadata-action tags input. See https://github.com/docker/metadata-action#tags-input. Config file value overrides this input if present.
    required: false
    default: |
      type=ref,event=branch
      type=ref,event=pr
      type=semver,pattern={{version}}
      type=semver,pattern={{major}}.{{minor}}
      type=semver,pattern={{major}}
  metadata-flavor:
    description: Docker metadata-action flavor input. See https://github.com/docker/metadata-action#flavor-input. Config file value overrides this input if present.
    required: false
    default: latest=false
  sources:
    required: true
    description: |
      List of source images to combine (one per line).
      Can be full image references with digests (e.g., org/image@sha256:abc123)
      or image references with tags (e.g., org/image:1.0.0-amd64)
outputs:
  manifest:
    description: The created manifest reference (first tag from metadata)
    value: ${{ steps.create.outputs.manifest }}
  tags:
    description: All tags generated by metadata-action (newline separated)
    value: ${{ steps.meta.outputs.tags }}
  metadata-json:
    description: JSON output from metadata-action
    value: ${{ steps.meta.outputs.json }}

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-user }}
        password: ${{ inputs.dockerhub-password }}

    - id: config
      name: Read docker config
      shell: bash
      env:
        DOCKER_CONFIG_FILE: ${{ inputs.docker-config-file }}
      run: ${{ github.action_path }}/../shared/read-docker-config.sh "$DOCKER_CONFIG_FILE"

    - id: resolve-image-name
      name: Resolve image name
      shell: bash
      env:
        INPUT_IMAGE_NAME: ${{ inputs.image-name }}
        CONFIG_IMAGE_NAME: ${{ steps.config.outputs.image-name }}
      run: |
        # Use input if provided, otherwise use config
        if [ -n "$INPUT_IMAGE_NAME" ]; then
          echo "image-name=${INPUT_IMAGE_NAME}" >> $GITHUB_OUTPUT
        else
          echo "image-name=${CONFIG_IMAGE_NAME}" >> $GITHUB_OUTPUT
        fi

    - id: resolve-metadata
      name: Resolve metadata inputs
      shell: bash
      env:
        INPUT_METADATA_TAGS: ${{ inputs.metadata-tags }}
        INPUT_METADATA_FLAVOR: ${{ inputs.metadata-flavor }}
        CONFIG_METADATA_TAGS: ${{ steps.config.outputs.metadata-tags }}
        CONFIG_METADATA_FLAVOR: ${{ steps.config.outputs.metadata-flavor }}
      run: |
        # Use config value if present, otherwise use input
        if [ -n "$CONFIG_METADATA_TAGS" ]; then
          echo "metadata-tags=${CONFIG_METADATA_TAGS}" >> $GITHUB_OUTPUT
        else
          echo "metadata-tags=${INPUT_METADATA_TAGS}" >> $GITHUB_OUTPUT
        fi

        if [ -n "$CONFIG_METADATA_FLAVOR" ]; then
          echo "metadata-flavor=${CONFIG_METADATA_FLAVOR}" >> $GITHUB_OUTPUT
        else
          echo "metadata-flavor=${INPUT_METADATA_FLAVOR}" >> $GITHUB_OUTPUT
        fi

    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ steps.resolve-image-name.outputs.image-name }}
        flavor: ${{ steps.resolve-metadata.outputs.metadata-flavor }}
        tags: ${{ steps.resolve-metadata.outputs.metadata-tags }}

    - name: Create manifest
      id: create
      shell: bash
      env:
        IMAGE_NAME: ${{ steps.resolve-image-name.outputs.image-name }}
        METADATA_TAGS: ${{ steps.meta.outputs.tags }}
        SOURCES: ${{ inputs.sources }}
      run: |
        # Convert newline-separated tags from metadata to comma-separated
        TAGS=$(echo "$METADATA_TAGS" | sed 's|^[^:]*:||' | paste -sd ',' -)

        echo "Generated tags: $TAGS"

        ${{ github.action_path }}/create-manifest.sh \
          "$IMAGE_NAME" \
          "$TAGS" \
          "$SOURCES"
